spring:
  batch.job.enabled: false # CommandLineRunner 설정 해제
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev-aurora-payment-cluster.cluster-c9cx6a2jazb5.ap-northeast-2.rds.amazonaws.com:3306/Payment?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: cpd_payment
    password: Cpd_payment)$20